{
    "source_id": "vcdb",
    "timeline": {
        "incident": {
            "year": 2019,
            "month": 12
        }
    },
    "victim": {
        "country": [
            "US"
        ],
        "region": [
            "019021"
        ],
        "victim_id": "Center for Health Care Services",
        "employee_count": "10001 to 25000",
        "industry": "62133",
        "locations_affected": 1,
        "state": "TX"
    },
    "action": {
        "malware": {
            "variety": [
                "Ransomware"
            ],
            "vector": [
                "Unknown"
            ]
        }
    },
    "actor": {
        "external": {
            "variety": [
                "Organized crime"
            ],
            "motive": [
                "Financial"
            ]
        }
    },
    "asset": {
        "assets": [
            {
                "variety": "S - Unknown"
            }
        ],
        "cloud": [
            "Unknown"
        ],
        "role": [
            "IT"
        ]
    },
    "attribute": {
        "confidentiality": {
            "data": [
                {
                    "variety": "Medical"
                }
            ],
            "data_victim": [
                "Patient"
            ],
            "state": [
                "Stored"
            ],
            "data_disclosure": "Potentially"
        },
        "integrity": {
            "variety": [
                "Software installation"
            ]
        },
        "availability": {
            "variety": [
                "Obscuration"
            ]
        }
    },
    "discovery_method": {
        "external": {
            "variety": [
                "Actor disclosure"
            ]
        }
    },
    "plus": {
        "event_chain": [
            {
                "action": "unk",
                "actor": "ext",
                "asset": "srv",
                "attribute": "cp",
                "summary": "somehow gained access to the environment"
            },
            {
                "action": "mal",
                "actor": "ext",
                "asset": "srv",
                "attribute": "ia",
                "summary": "malware installed"
            },
            {
                "action": "mal",
                "actor": "ext",
                "asset": "srv",
                "attribute": "cp",
                "summary": "potentially stole stuff"
            },
            {
                "action": "mal",
                "actor": "ext",
                "asset": "srv",
                "attribute": "au",
                "summary": "Encrypted stuff"
            }
        ],
        "sub_source": "phidbir",
        "modified": "2020-10-22T18:34:52.867Z",
        "created": "2020-10-22T18:34:52.867Z",
        "timeline": {
            "notification": {
                "year": 2019,
                "month": 12,
                "day": 27
            }
        },
        "master_id": "fee0cbd4-6241-4ff2-9b50-826f47c178d0",
        "analysis_status": "Validated",
        "analyst": "planglois",
        "dbir_year": 2021,
        "attribute": {
            "confidentiality": {
                "data_abuse": "Unknown"
            }
        },
        "github": "14766"
    },
    "incident_id": "8f273660-146b-11eb-ac54-3bea5c26f172",
    "security_incident": "Confirmed",
    "reference": "https://www.databreaches.net/tx-san-antonio-mental-health-and-substance-abuse-services-provider-hit-by-ransomware-attack/",
    "summary": "Center for Health Care Services, in San Antonio Texas, experienced a ransomware attack",
    "confidence": "High",
    "targeted": "Opportunistic",
    "schema_version": "1_3_4"
}